@endpoint = http://localhost:3000

############
# Internal #
############
GET {{endpoint}}/internal/products HTTP/1.1

############
# External #
############
GET {{endpoint}}/external/products HTTP/1.1
