@endpoint = http://localhost:3000

##########################
# Versioning in url path #
##########################
### v1
GET {{endpoint}}/v1/products

### v2
GET {{endpoint}}/v2/products

#################################
# Versioning in query parameter #
#################################
### v1
GET {{endpoint}}/products?api-version=v1

### v2
GET {{endpoint}}/products?api-version=v2

#############################################
# Versioning in headers using custom header #
#############################################
#
# Note: Below samples return 404.
#
### v1
GET {{endpoint}}/products HTTP/1.1
Api-Version: v1

### v2
GET {{endpoint}}/products HTTP/1.1
Api-Version: v2

##########################################################
# Versioning in headers using content negotiation header #
##########################################################
#
# Note: Below samples return 404.
#
### v1
GET {{endpoint}}/products HTTP/1.1
Accept: application/json; charset=utf-8; api-version=v1

### v2
GET {{endpoint}}/products HTTP/1.1
Accept: application/json; charset=utf-8; api-version=v2

####################################
# Both version and revision in use #
####################################
### v1
GET {{endpoint}}/products;rev=2?api-version=v1 HTTP/1.1

### v2
GET {{endpoint}}/products;rev=2?api-version=v2 HTTP/1.1
