@endpoint = http://localhost:3000

########
# JSON #
########
GET {{endpoint}}/products HTTP/1.1
Accept: application/json; charset=utf-8

#######
# Xml #
#######
#
# Note: Just for discussion purposes since
# it does not return real xml.
#
GET {{endpoint}}/productsxml HTTP/1.1
Accept: application/xml
