@endpoint = http://localhost:3000

#########
# Path  #
#########
GET {{endpoint}}/products HTTP/1.1

###
GET {{endpoint}}/products/1/parts HTTP/1.1

###
GET {{endpoint}}/products/1/parts/101 HTTP/1.1
