@endpoint = http://localhost:3000

##################
# Flat structure #
##################
#
# - Prices are part of the top level entity.
#
GET {{endpoint}}/products1 HTTP/1.1

#################
# Sub structure #
#################
#
# - Price has child entity and price per currency.
#
GET {{endpoint}}/products2 HTTP/1.1
