@endpoint = http://localhost:3000

###########
# No auth #
###########
GET {{endpoint}}/products HTTP/1.1

### Response:
# HTTP/1.1 200 OK
#
# [
#   {
#     "id": 1,
#     "name": "Bike"
#   }
# ]

#########################
# Subscription key auth #
#########################
### In header
GET {{endpoint}}/products HTTP/1.1
Ocp-Apim-Subscription-Key: abcdedf1234567890

### In query parameter
GET {{endpoint}}/products?subscription-key=abcdedf1234567890 HTTP/1.1

### Response:
# HTTP/1.1 200 OK
#
# [
#   {
#     "id": 1,
#     "name": "Bike"
#   }
# ]

##############
# Basic auth #
##############
#
# Note: Base64 is used for encoding of the username and password.
#
GET {{endpoint}}/products HTTP/1.1
Authorization: Basic dXNlcjpIaSFZb3VTbWFydExpdHRsZUZlbGxvdw==

### Response:
# HTTP/1.1 200 OK
#
# [
#   {
#     "id": 1,
#     "name": "Bike"
#   }
# ]

##################
# OAuth 2.0 auth #
##################
#
# Protect a web API backend in Azure API Management by using OAuth 2.0 authorization with Azure AD
# https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad
# 
# Secure an Azure API Management API with Azure AD B2C
# https://docs.microsoft.com/en-us/azure/active-directory-b2c/secure-api-management
#
GET {{endpoint}}/products HTTP/1.1
Authorization: Bearer eyJ0eXA...2000.characters.removed...ahl8nUmD73TkhyA

### Response:
# HTTP/1.1 200 OK
#
# [
#   {
#     "id": 1,
#     "name": "Bike"
#   }
# ]

###########################
# Client certificate auth #
###########################
#
# Follow Rest Client instructions how to setup client certificates
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#
GET {{endpoint}}/products HTTP/1.1

### Response:
# HTTP/1.1 200 OK
#
# [
#   {
#     "id": 1,
#     "name": "Bike"
#   }
# ]
